language: node_js

script:
  - npm run prettier:check
  - npm run lint
  - npm run build
  - npm test

before_deploy:
  - npm pack

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: "xml-to-react-loader-*.tgz"
    skip_cleanup: true
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: "jacob.t.fischer@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
